# 备份

port: 7890
socks-port: 7891
allow-lan: true
mode: Rulelog-level: info
external-controller: 127.0.0.1:9090
dns: enable: true 
ipv6: false
listen: 127.0.0.1:5000
enhanced-mode: fake-ip
nameserver:
 - 119.29.29.29
 - 114.114.114.114
 - 223.5.5.5
 - 180.76.76.76
 - 1.2.4.8
# - tls://sdns.kbsml.com
# - https://dns-api.trli.xyz/dns-query
# - https://sdns.kbsml.com/dns-query
fallback:
 - 208.67.222.222
 - 1.0.0.1
 - 8.8.8.8
 - 9.9.9.9
 - 208.67.222.222
 - 208.67.220.220

Proxy:
- { name: "Unlock", type: neteasemusic }

Proxy Group:
- { name: "NeteaseMusic", type: select, proxies: ["Unlock", "DIRECT"] }

Rule:
# Unblock NeteaseMusic
- DOMAIN,api.iplay.163.com,NeteaseMusic
- DOMAIN,apm3.music.163.com,NeteaseMusic
- DOMAIN,apm.music.163.com,NeteaseMusic
- DOMAIN,interface3.music.163.com,NeteaseMusic
- DOMAIN,interface.music.163.com,NeteaseMusic
- DOMAIN,music.163.com,NeteaseMusic
- IP-CIDR,39.105.63.80/32,NeteaseMusic
- IP-CIDR,45.254.48.1/32,NeteaseMusic
- IP-CIDR,47.100.127.239/32,NeteaseMusic
- IP-CIDR,59.111.160.195/32,NeteaseMusic
- IP-CIDR,59.111.160.197/32,NeteaseMusic
- IP-CIDR,59.111.181.35/32,NeteaseMusic
- IP-CIDR,59.111.181.38/32,NeteaseMusic
- IP-CIDR,59.111.181.60/32,NeteaseMusic
- IP-CIDR,101.71.154.241/32,NeteaseMusic
- IP-CIDR,103.126.92.132/32,NeteaseMusic
- IP-CIDR,103.126.92.133/32,NeteaseMusic
- IP-CIDR,112.13.119.17/32,NeteaseMusic
- IP-CIDR,112.13.122.1/32,NeteaseMusic
- IP-CIDR,115.236.118.33/32,NeteaseMusic
- IP-CIDR,115.236.121.1/32,NeteaseMusic
- IP-CIDR,118.24.63.156/32,NeteaseMusic
- IP-CIDR,193.112.159.225/32,NeteaseMusic
- IP-CIDR,223.252.199.66/32,NeteaseMusic
- IP-CIDR,223.252.199.67/32,NeteaseMusic
# Advertising
- DOMAIN,admusicpic.music.126.net,REJECT
- DOMAIN,iadmat.nosdn.127.net,REJECT
- DOMAIN,iadmusicmat.music.126.net,REJECT
- DOMAIN,iadmusicmatvideo.music.126.net,REJECT
- MATCH,DIRECT
