port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5000
  enhanced-mode: fake-ip
  nameserver:
     - 223.5.5.5
     - 180.76.76.76
     - 119.29.29.29
     - 117.50.10.10
     - 114.114.114.114
  fallback:
     - 8.8.8.8
     - 1.1.1.1